### PR TITLE
document added to show you how to run tribe-app locally

### PR DESCRIPTION
**Pull request by codemechanica**
Saved as a pdf file instead of txt for better formatting

### CODE REVIEW

**Comment by haxwell** [comment]
Thank you for this! A few edits.. 

1. where it says Java, it should refer to Java 19. 
2. At the tail of 'c.' just before part 'd.', I would add ```If you see tribeapp_db listed above, it is okay, it just means tribeapp has been previously set up, and you will need to drop the existing database. [Then show the command] ```

```DROP DATABASE tribeapp_db```
3. Commands 'g' and 'h' are not necessary, they can be removed.

You might note that while you will likely be re-creating the database often, you will only ever need to create the user and grant permissions, once.

Also, 5a, you can remove `ionic`. Only `ionic serve` is useful.

**Comment by haxwell** [comment]
Also, as a rule, we don't keep anything that is output in our code repository. Only source code. This is because source code can be version controlled, while output cannot. And even if it could, it's still a better idea to be version controlling the source.

So, that means we need the file you used to create the PDF, it needs to be included as well. And let's create a directory named 'doc' and put these two files (source and pdf) there for now.

**Comment by fmigsystems** [comment]
I created the pdf using google docs which is online only so I don't have a separate file that I used to create the PDF.

**Comment by haxwell** [comment]
Okay, so I've thought about this a bit more, and I think I have a more complete solution. 

So, this getting started page, will be a proper web page in our Mock Programming Job website. In fact, it will BE the website, until we get around to designing the rest. You would go to mockprogrammingjob.com and see this Getting Started page.

I've created an issue for us to discuss things at https://github.com/savvato-software/mock-programming-job-website/issues/1

**Comment by haxwell** [comment]
In the repo itself, we need to use text files. It's just the simplest way overall.

You can use Markdown which is a way to format text so that it displays with proper headers, lists, formatting, etc.

The textboxes here on github use Markdown.

So that to say, any documentation we store in the repo itself, should be text, and formatted in Markdown, if need be.

**Comment by fmigsystems** [comment]
I'll discuss with you in more detail about the documentation in our upcoming meeting.

**Pull request closed without merging**
