### PR TITLE
TRIB-272: updates testing by separating unit tests and integration tests

### PR DESCRIPTION
**Pull request by mrsbluerose**
This initial pull request is my first pass at solving this problem. We'll need to discuss and make changes.

I also wanted to see how these testing changes affected our current CI/CD scripts by submitting this pull request. I'm watching to see if we can tell if the tests run (both unit and integration)

Changes:
- updated pom mvn sure-fire plugin configuration (for unit tests) and added mvn fail-safe plugin (for integration tests)
- added pom mvn sure-fire report plugin to generate html reports that show details about executed tests
- created two directories under tests (unit, integration)
  - moved service tests to the unit folder
  - moved controller tests to the integration folder (existing backlog tickets have us changing these to unit tests, but for now, they are integration tests)
- renamed all integration tests with the `*IT` naming convention

Outcomes:
- `mvn test` runs all unit tests
- `mvn surefire-report:report-only` generates an html report that you can open in browser (target > surefire-reports > surefire-report.html)
- `mvn verify` runs all integration tests
- `mvn surefire-report:failsafe-report-only` generates an html report (target > surefire-reports > failsafe-report.html)

Notes:
- In the refactoring process (renaming, moving files and updating imports), IntelliJ seems to have removed several unused imports in the files. Some sort of automatic clean up. It did not get all unused imports, but it did remove several, such as Constants and UserRole in the NotificationsAPI controller. I did not notice these until they were already pushed.
- This pull request will mean that unit tests must be placed in the unit directory and named `*Test` and that integration tests must be placed in the integration directory and named `*IT`.

Still needed:
- second pair of eyes on test directory structure to make sure I didn't break anything
- second pair of eyes on the test results
- thoughts on naming conventions
- verify CI/CD still works on all testing

### CODE REVIEW

**Comment by mrsbluerose** [comment]
The unit tests seemed to run, but I cannot verify whether or not the integration tests ran. There is an error with our codecov report:

image

**Comment by mrsbluerose** [comment]
The jacoco error fixed:
- updated pom jacoco plugin to test on the "verify" level
- updated the codecov .yml to test on verify

This removed the jacoco error and all tests passed.
A few moments later, it failed with the codecov/project — 15.27% (target 75.00%) message
image

This is a problem we've had in the past. Where are these numbers coming from? What is only being measured as 15.27%?

**Comment by mrsbluerose** [comment]
Troubleshooting:

Codecov report for this commit (head):
image

the base it is comparing to (the last approved and merged pull request):
image

The link it has in the bad report says this error comes from the last commit not having a report: https://docs.codecov.com/docs/error-reference#missing-base-report

**Comment by mrsbluerose** [comment]
re-ran checks on the last approved pull request #271 and confirmed this error in the logs:
image

**Comment by mrsbluerose** [comment]
found that error on a few other pull requests, and they didn't seem to have a problem. This error is so random. Stepping away. I did find this post to read later to see if it's related: https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857

**Comment by mrsbluerose** [comment]
> found that error on a few other pull requests, and they didn't seem to have a problem. This error is so random. Stepping away. I did find this post to read later to see if it's related: https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857

Dug back in. Not sure if this is the problem or not. We seem to be using version 3. We have the secret token in place. We could try upgrading to version 4.

**Comment by mrsbluerose** [comment]
correction. We are using version 4 of codecov. I tried re-running the codecov github actions on previous pull requests that also say they didn't upload reports. I don't want to over do that and use up the account workflow limits. I'll show what I found in Thursday's meeting.

**Review by haxwell — APPROVED** [review]

**Pull request merged**
