### PR TITLE
ToBeReviewedCheckerService, make use of Merriam-Webster dictionary API.

### PR DESCRIPTION
**Pull request by haxwell**
The impetus to this PR is in ToBeReviewedCheckerService. I had to make some small changes to get the Merriam Webster API working in replacement for Words API.

Then, I got into testing it, and discovered the jacoco plugin was erroring out. And it was printing the a stack trace each time Mockito created a mock, etc. So the changes in pom.xml came from trying to correct those errors.

### CODE REVIEW

**Review by mrsbluerose — COMMENTED** [review]
As is, this build fails on my machine when I run mvn verify. ChatGPT suggests it's because jacoco is defined in two places. It works when I comment out the argline in properties. 

I can share screens if we want to troubleshoot. I don't quite understand what error you were correcting.

**Comment by haxwell** [comment]
You may need to upgrade Maven.. I had 3.6 or something close before and I had to upgrade to 3.9.9. I went down the same path with chatGPT.. It's not wrong, but not the correct answer either.

**Comment by mrsbluerose** [comment]
> You may need to upgrade Maven.. I had 3.6 or something close before and I had to upgrade to 3.9.9. I went down the same path with chatGPT.. It's not wrong, but not the correct answer either.

Okay. I checked and I'm on 3.9.6. 
Are you able to run the tests directly in IntelliJ? On this branch, I was able to run the unit tests on the command line with mvn test.
mvn verify runs unit tests (which may be a bug with my work) but cannot run the integration tests. 
No tests will run in IntelliJ.

**Comment by haxwell** [comment]
Audra tested it on her box and all was good!

**Pull request merged**
