### PR TITLE
not sure if everything is correct but take a look at it

### PR DESCRIPTION
**Pull request by codemechanica**

### CODE REVIEW

**Comment by haxwell** [comment]
@codemechanica Try running the code and see if it does what you want it to. If not, think about what is missing, or needs to be changed. That is your next step! :v:

**Comment by haxwell** [comment]
Sun.. See my previous comment from a month ago! Try running the code!

**Comment by codemechanica** [comment]
Everything looks good on my end

**Comment by codemechanica** [comment]
Not sure why the build is failing. I can run backend successfully

**Comment by codemechanica** [comment]
Got this back from chat gpt:
The com.sun.tools.javac.tree.JCTree$JCImport class is part of the Java Compiler API, specifically the Java Compiler Tree API. This API is not part of the official Java SE specification, and classes in the com.sun.tools.javac package are considered internal and subject to change without notice.

I think this implies code modification but I don't think this is the way to go. Again, I can run from the command line with no issues although it fails from intellij.

**Comment by codemechanica** [comment]
So it turns out it that I did not have oracle jdk installed. The issue of not being able run in intellij remains unresolved and I will hand off this ticket to one of the other backend engineers.

**Pull request closed without merging**
